### PR TITLE
Update luna deps and remove patch

### PR DESCRIPTION
**Pull request by sergeichestakov**
Looking into [this bug](https://linear.app/replit/issue/WS-660/errors-containing-cross-site-scripts-dont-show-up-in-error-webview). I have a hunch that we're seeing errors from [`luna-console`](https://www.npmjs.com/package/luna-console) because our fork of Eruda is still stuck on a really old version. Currently, we're using `0.3.1` whereas the latest version (which the upstream repo has since upgraded to) is `1.3.3`.

While I'm not 100% certain the bug will be fixed I think it's good to get us upgraded regardless and then see if this still repros. Had to also add the remaining luna deps from upstream in order to get this to build. Also removed the patch we were using for luna console since that was targeting a stale version and may no longer be relevant.

Once this is merged, I will run `yarn build` and paste the outputted build file in our [devtools Repl](https://replit.com/@util/replco#devtools_dev/src/devtools/eruda-patched.js) to ship this. Not entirely sure the best way to test tbh but this feels pretty harmless

### CODE REVIEW

**Review by gburtini — APPROVED** [review]
Our dev/ops process for this is uh, very challenging, so please make sure you're available to help undo anything you actually do ship in case it goes wrong.

**Comment by sergeichestakov** [comment]
thanks yeah will do 🤞

**Comment by masad-frost** [comment]
@sergeichestakov revert this if it didn't materialize. We can brainstorm through next steps for the devtools.

**Comment by sergeichestakov** [comment]
done, thanks: https://github.com/replit/eruda/pull/9

**Comment by sergeichestakov** [comment]
and yeah I think we should kill it. see discussion [here](https://replit.slack.com/archives/C030RJ2PRC7/p1692047834434879?thread_ts=1692046434.693099&cid=C030RJ2PRC7)

**Pull request merged**
